### ISSUE TITLE
video_demo.py line 99

### ISSUE THREAD

**Issue by zhangxgu** [zhreshold/mxnet-yolo#22]
Hi, I find that  line 99 in video_demo.py  the code feed "res" to get _bboxes. But is this "res" right? Maybe it should be "result" since in line 98 we have **result.append(res)**  .

**bboxes = get_bboxes(frm,res)**

**Comment by zhangxgu** [comment]
@zhreshold

**Comment by zhreshold** [comment]
@liumusicforever Can you have a look?

**Comment by liumusicforever** [comment]
@zhangxgu Thanks for finding the problem , It's the consider error , I pass **res** to calling **get_bboxes** because I always set batch_size = 1 when testing , and the range of **detection.shape[0]** are always 1, If batch_size are bigger then one , the code should `modify to :
```python
# result = []  << didn't used , can be deleted
for i in range(detections.shape[0]):
        det = detections[i, :, :]
        res = det[np.where(det[:, 0] >= 0)[0]]
        # result.append(res)  << didn't used , can be deleted
        bboxes = get_bboxes(frm,res)
        record.append([t,bboxes])
```

I will update when I have time , or you can change directly.

Thanks !!

**Comment by zhangxgu** [comment]
@liumusicforever ,thank you for your help!! I can change myself :)
